### PR TITLE
Restyle Theme

### PR DESCRIPTION
**Pull request by lewis-dbi**
Resolves https://github.com/deliciousbrains/wp-db-backup/issues/10

### Theme Restyling

I'd say this is 95% there. I just need some dev help on a couple of things so I can complete the restyling.

Still,  you may as well go ahead and give it a test!

FYI, I haven't created an issue for this.

I've also worked through some UX & accessibility improvements:

- Adding focus/active states to buttons
- Adding labels to form elements where missing previously
- Making checkboxes and radio button labels clickable.
- A few responsive fixes
- Keyboard tabbing fix
- Styled a few other states (e.g. next backup date messaging and action)

CleanShot 2021-12-12 at 18 41 39@2x

---

### Still to do

I do need help with the following:

- Move the scheduled backup code and content to the schedule backup tab/page

- Move plugin related notices to this container, below the nav:
CleanShot 2021-12-12 at 18 36 15@2x

- Move "backup running" panel to be above the "Tables" panel.

CleanShot 2021-12-12 at 18 38 37@2x

^Similarly to above, remove the progress % indicator (e.g. 100%) from the progress bar and place it above the progress bar as per the mockups:

CleanShot 2021-12-12 at 18 40 40@2x

- Lastly, there is a hidden div here, only triggered when an error is thrown. It's creating additional whitespace at the bottom of the panel. Are we able to make this hidden unless it contains content?

CleanShot 2021-12-12 at 18 42 58@2x

---

### Summary

It's almost there.

 One thing to be conscious of is there are quite a few error states in the code that seem to be pretty circumstantial, and I haven't been able to trigger them in testing. 

IIRC, we also faced an issue with the Migrate header whereby global WP notices pushed it down the page a little and made it look a little strange. It's such a small issue though that I'll leave it up to you if we should fix it. This has only just popped into my head as I write this PR

We may have gone a little far with this in terms of implementation, but once you get stuck into it, it's hard to ignore other obvious errors/issues that have obvious fixes.

### CODE REVIEW

**Comment by mauryaratan** [comment]
Hey @lewis-dbi! I've taken care of the changes, could you please take a look and let me know if all looks good?

**Comment by lewis-dbi** [comment]
@mauryaratan Thanks Ram!

Couple of things:

- Is it safe to add `display:none` to `<iframe id="backuploader">`? It's adding white-space underneath the "backup is running" panel. If not, no worries. It's a minor thing.

- After you download a backup, the scheduled backups tab has additional white space at the top. Is this easy to fix?

CleanShot 2021-12-13 at 13 23 08@2x

- Lastly, are we able to wrap the title and info text here inside another div so I can style them?

CleanShot 2021-12-13 at 13 24 37@2x

Thanks!

**Comment by mauryaratan** [comment]
@lewis-dbi should be good now. You can add your styles `#instructions-container` for additional tables.

**Comment by lewis-dbi** [comment]
@mauryaratan Thanks, fixed up my changes too!

This still happens for me, but only appears a short while after the backup is at 100% completion:

CleanShot 2021-12-14 at 19 04 04@2x

**Comment by polevaultweb** [comment]
@mauryaratan looks like some of the errors aren't displaying properly:

image

Can you spoof the code to show errors to make sure they all display correctly.

@lewis-dbi the styling of the tables doesn't seem to appearing correctly for me

image

**Comment by mauryaratan** [comment]
@polevaultweb Both errors fixed!

Looks like when `SCRIPT_DEBUG` was set to true, it was changing the stylesheet order. Since the styling in the plugin is very specific to the actual element, `common.css` was interfering with styles.

I added `common.css` as a dependency for our styles which fixes most of the layout/spacing issues.

@lewis-dbi Can you please take a look at this again? You may want to add `define( 'SCRIPT_DEBUG', true );` to your wp-config.php, for sake of consistency.

**Comment by lewis-dbi** [comment]
When I turn `define( 'SCRIPT_DEBUG', true );` on, I see the table issue you see @polevaultweb . There are a few other visual bugs that appear for me too when this is on. Just things like alignment issues etc.

How should I proceed here?

Also, @mauryaratan, is there a way for me to view all errors to make sure they appear in the right place like like the success notice?

**Comment by mauryaratan** [comment]
> @mauryaratan Is there a way to make sure our styling changes are last in the stack, overriding everything else?

I made that change in the last commit, so the default common.css is added before our styles.

> Also, is there a way for me to view all errors to make sure they appear in the right place like like the success notice?

That'd require some manual PHP code but for what its worth, I spoofed the errors and success message in my last commit and made sure they appear in the right place.

It was appearing on top because of core JS functionality in WordPress. Adding `inline` class on each instance of `error` class fixed that.

**Comment by lewis-dbi** [comment]
@mauryaratan Ah ok. there are still a few visual bugs for me. alignments and margins off etc.

do I just need to go through and add manual fixes then? or is there a more efficient way.

> That'd require some manual PHP code but for what its worth, I spoofed the errors and success message in my last commit and made sure they appear in the right place.

Ok thanks 👍

**Pull request merged**
